spring.flyway.url=jdbc:postgresql://localhost:5432/lab_reactive_db
spring.flyway.user=postgres
spring.flyway.password=admin123

spring.flyway.enabled=true

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/lab_reactive_db
spring.r2dbc.username=postgres
spring.r2dbc.password=admin123

spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true